### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by inPhilly** [shinobicontrols/iOS9-day-by-day#14]
I love your tutorials, but I don't understand why you don't offer them in objective c any more.

**Comment by Mattwebber93** [comment]
Hi, we try to provide as much support for our users as possible with a wide range of downloadable samples as well as online tutorials and blog posts. However we only have a limited resource that we can dedicate to producing the material we offer. Therefore we must decide what language to provide these in, and as Swift is now beginning to reach maturity and Apple is steering ever more towards it we feel it is better to make the tutorials reflect this.

We do provide many samples in Objective-C which could help you to translate between Swift and Objective-C. Alternatively there are many freely available resource online which could help.

Matt - Shinobi Controls Developer
